site_name: The safedata_validator package
repo_url: https://github.com/ImperialCollegeLondon/safedata_validator/
theme:
  name: material
markdown_extensions:
  - admonition
  - markdown_include.include
plugins:
  - search
  - mkdocstrings
extra_css:
  - custom.css
use_directory_urls: false
nav:
  - 'Overview': 'index.md'
  - 'Data providers':
    - 'Overview': 'data_providers/overview.md'
    - 'Data availability': 'data_providers/availability.md'
    - 'Excel format details':
      - 'Overview': 'data_providers/data_format/overview.md'
      - 'Summary worksheet': 'data_providers/data_format/summary.md'
      - 'Taxa worksheets': 'data_providers/data_format/taxa.md'
      - 'GBIFTaxa worksheet': 'data_providers/data_format/gbif_taxa.md'
      - 'NCBITaxa worksheet': 'data_providers/data_format/ncbi_taxa.md'
      - 'Locations worksheet': 'data_providers/data_format/locations.md'
      - 'Data worksheets': 'data_providers/data_format/data.md'
      - 'Other file formats': 'data_providers/data_format/other_formats.md'
      - 'Data format FAQs': 'data_providers/data_format/faqs.md'
  - 'Command line tools':
    - 'overview': 'command_line_tools/overview.md'
    - 'safedata_validate': 'command_line_tools/safedata_validate.md'
    - 'safedata_zenodo': 'command_line_tools/safedata_zenodo.md'
  - 'Developers':
    - 'API Reference':
      - 'Overview': 'api/overview.md'
      - 'Resources': 'api/resources.md'
      - 'LocalDB': 'api/taxondb.md'
      - 'Logger': 'api/logger.md'
      - 'Extents': 'api/extent.md'
      - 'Summary': 'api/summary.md'
      - 'Locations': 'api/locations.md'
      - 'Fields and dataworksheets': 'api/field.md'
      - 'Taxa': 'api/taxa.md'
      - 'Zenodo': 'api/zenodo.md'
    - 'Build notes': build_notes.md
  - 'Installation and configuration':
    - 'Installation': 'install/install.md'
    - 'Configuration': 'install/configuration.md'
    - 'Building local GBIF': 'install/build_local_gbif.md'
    - 'GBIF validation notes': 'install/gbif_validation.md'
    - 'Building local NCBI': 'install/build_local_ncbi.md'
    - 'NCBI validation notes': 'install/ncbi_validation.md'
