site_name: Data at the SAFE Project
repo_url: https://github.com/ImperialCollegeLondon/safedata_validator/
theme: material
markdown_extensions:
  - admonition
plugins:
  - search
  - mkdocstrings
extra_css:
  - custom.css
use_directory_urls: false
nav:
  - 'Introduction': 'index.md'
  - 'Data availability': 'availability.md'
  - 'Data format overview': 'data_format/overview.md'
  - 'Other file formats': 'data_format/other_formats.md'
  - 'Excel format details':
    - 'Summary worksheet': 'data_format/summary.md'
    - 'Taxa worksheet': 'data_format/taxa.md'
    - 'Locations worksheet': 'data_format/locations.md'
    - 'Data worksheets': 'data_format/data.md'
    - 'Data format FAQs': 'data_format/faqs.md'
  - 'Package details':
    - 'Usage': 'usage/usage.md'
    - 'Installation': 'usage/install.md'
    - 'Building local GBIF': 'usage/build_local_gbif.md'
    - 'GBIF validation notes': 'usage/gbif_validation.md'
  - 'API Reference':
    - 'Resources': 'api/resources.md'
    - 'Logger': 'api/logger.md'
    - 'Extents': 'api/extent.md'
  - 'Build notes': build_notes.md
