name: Python unit tests

on: [push, pull_request]

env:
  # This env variable stops the safedata_validator test suite from
  # testing against remote taxa APIs (slow and throttled) except on
  # master or release branches
  SDV_NO_REMOTE: ${{ ! (contains(github.ref, 'master') || contains(github.ref, 'release'))  }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # In order to avoid throttling from remote APIs, only run one job at
      # a time on master and release branches. Note that env.SDV_NO_REMOTE
      # is only available within job steps, and not here. 
      max-parallel: ${{ fromJSON('[12, 1]')[ (contains(github.ref, 'master') || contains(github.ref, 'release')) ] }}
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest
